### ISSUE TITLE
[Bug] Nhentai plugin no longer works, and the issue is not the new plugin.

### ISSUE THREAD

**Issue by zeldatp151** [hkalexling/mango-plugins#28] opened 2022-05-01 21:14 UTC
**Plugin**
nhentai

**Describe the bug**
neither the new plugin, nor the plugin from last year work on nhentai now, I think something has changed on the nhentai.net site.
now when I try to download from nhentai, I get the following error "Failed to list chapters. Error: Error: Failed to get gallery title"

**To Reproduce**
1. try to use the nhentai plugin in mango to download any manga

**Expected behavior**
I expect the manga to be downloaded

**Screenshots**

**Mango version**
E.g., v0.26.2

**Additional context**
I have debug logging turned on, and even with that I still only get the following when trying to download from nhentai
```
[DEBUG] Setting proxy
[DEBUG] Setting read timeout
[DEBUG] Requesting https://nhentai.net/g/97295/
[DEBUG] Performing request
[ERROR] Failed to get gallery title
[DEBUG] 200 GET /api/admin/plugin/list?plugin=nhentai&query=https%3A%2F%2Fnhentai.net%2Fg%2F97295%2F 92.23ms
```
each time I try

**Comment by hkalexling** [comment] 2022-05-03 11:19
I couldn't reproduce the issue. Does it work when you visit https://nhentai.net/g/97295/ directly from your browser?

**Comment by zeldatp151** [comment] 2022-05-03 11:54
It's working again, I don't know what happened, but for 2 days I tried to figure out what was going on before posting this bug, but now it just works again out of nowhere.

**Comment by hkalexling** [comment] 2022-05-03 12:04
I guess nhentai was down or showing an error message on https://nhentai.net/g/97295/. Since it can't be reproduced anymore I am closing this issue. Please feel free to reopen or comment if it happens again.

**Closed as completed by hkalexling** 2022-05-03 12:04 UTC
Labels: bug

**Comment by zeldatp151** [comment] 2022-05-08 19:20
Ok, it is now happening again, and it happens with ALL nhentai links, not any specific one. it's only a hunch, but I think it may be caused by cloudflare, I noticed that every time I go to the nhentai page, on any device, including my phone which is not on the same network, I has to do a check to verify the browser with cloudflare, maybe The plugin is either not able to pass the cloudflare check, or it times out before the check can complete.

**Comment by hkalexling** [comment] 2022-05-15 03:49
Yeah that sucks. All the plugin does is simply scrape the images, and passing the cloudflare check would be non-trivial because the whole point is to prevent DDOS attacks so any automation might be flagged.

**Comment by zeldatp151** [comment] 2022-05-15 15:46
It seems it does still work when cloudflare isn't being too strict, nothing to be done, not worth trying to write a bypass for cloudflare, just have to wait a day or 2 for it it normalize.
